# Generated by Django 4.0.6 on 2022-10-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profil_options'),
        ('projects', '0003_auto_20220418_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'project')},
        ),
    ]
