# Generated by Django 4.0.6 on 2022-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='how',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
